spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2_db
  datasource:
    url: jdbc:h2:tcp://localhost/~/test3
    username: sa
    password: 1
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
